apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grafana.yaml
- prometheus.yaml
- nginx.yaml
- apps/build.yaml
- host-external-service.yaml

patches:
  - target:
      kind: Deployment
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          env: local
        name: not-used
